name: Gitleaks Secret Scan

on:
  push:
  pull_request:

jobs:
  gitleaks-scan:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          # On force le scan du dossier actuel sans passer par l'historique Git
          # pour être sûr qu'il détecte le fichier .pem présent
          args: detect --source . --verbose --no-git
          exit-code: 1